# This is a config for E2B sandbox template.
# You can use template ID (j6th8uzinzc548m4pim6) or template name (vibe-nextjs-chang-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-chang-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-chang-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-chang-2')

team_id = "a906fff5-b646-4c98-9cce-0e75cb21910a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-chang-2"
template_id = "j6th8uzinzc548m4pim6"
